[package]
name = "data_funnel"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = { version = "1.0.66" }
rusqlite = { version = "0.32.1", features = ["bundled"] }
rand = { version = "0.8.5" }
tokio = { version = "1", features = ["full"] }
tokio-rustls = { version = "0.23" }
rustls = { version = "0.21" }
#zstd = { version = "0.11" }
#bytes = { version = "1.2" }
rustls-pemfile = { version = "1.0" }
chrono = { version = "0.4.38" }

[dev-dependencies]
tempfile = { version = "3.13.0" }
rcgen = { version = "0.13.1", features = ["pem"] }